### ISSUE TITLE
[Feature Request] Allow changing IP along port

### ISSUE THREAD

**Issue by Foxbond** [dpdearing/android-gps-emulator#13]
As title says.

**Comment by dpdearing** [comment]
Good request.  I'm not necessarily going to get to this soon, so feel free to submit a pull request if you'd like

**Comment by dpdearing** [comment]
Added in 569eacd

**Comment by dpdearing** [comment]
Included in [v0.2 release](https://github.com/dpdearing/android-gps-emulator/releases/tag/v0.2)
