### ISSUE TITLE
Cannot download GWT developer plugin 

### ISSUE THREAD

**Issue by durgaswaroop** [dpdearing/android-gps-emulator#14]
It goes to a 404 page when I click on the GWT download button.

**Comment by dpdearing** [comment]
Thanks for the report.  What OS, browser and browser version?  

The GWT plugin stopped being supported a while ago for many brwosers and this is still using an old version of GWT.  The project needs to be updated to a more recent version of GWT to get Super Dev Mode which doesn't require the GWT Developer Plugin but I haven't gotten around to it yet.

**Comment by dpdearing** [comment]
I updated the application to use GWT 2.8.0 which doesn't rely on the developer plugin.  The branch with these changes was merged into the master branch in 661af90

**Comment by dpdearing** [comment]
Included in [v0.2 release](https://github.com/dpdearing/android-gps-emulator/releases/tag/v0.2)
