### ISSUE TITLE
Doesnt work anymore?

### ISSUE THREAD

**Issue by luizfduartejr** [dpdearing/android-gps-emulator#15]
I run the AVD with my app and this tool and my app respond correctly to geo fix commands sent by my terminal, but doesnt by this tool. The port is ok, the tool says that is connected, but doesnt work.  Via telnet I've to inform my emulator auth token, how this tool know my token to do the same authentication if it doesnt ask me? Maybe is this the causa of the bad behavior.

**Comment by dpdearing** [comment]
Thanks for reporting this.  The auth token is likely the problem.  

I don't have time to fix it right now, but I'm open to a pull request!

**Comment by dpdearing** [comment]
This should be fixed in 019ffca.  I'll put up a new release version of an executable war after making a few other changes.

**Comment by dpdearing** [comment]
Included in [v0.2 release](https://github.com/dpdearing/android-gps-emulator/releases/tag/v0.2)

**Comment by luizfduartejr** [comment]
Awesome! Thanks for the great work!
