### ISSUE TITLE
Error connecting to localhost:5554 - Connection refused: connect error

### ISSUE THREAD

**Issue by RiccoSuave** [dpdearing/android-gps-emulator#16]
I am using Chrome and Windows 10; do I need to update Windows firewall to permit 5554? I did add a rule to allow 5554, and yet I still get an error as follows: "Error connecting to localhost:5554 - 0" 
Given that I am very new at programming, could you tell me what language this uses, so I can learn more about it?

**Comment by dpdearing** [comment]
Do you have the emulator up and running before trying to connect?  I think it tries to auto-connect at launch, so you may need to press the Connect button to try again.

Other than that, I don't have a Windows machine with the Android emulator to test against, so I can't try to reproduce the problem.  I wouldn't expect Windows to block a localhost connection, but I really don't know.  Sorry I can't be more help.

The program is written in Java and uses GWT.

**Comment by veitk** [comment]
i have the same message, but i think the problem is: it only works on the emulator. i want to forward this to my real device. any hints for that?

**Comment by dpdearing** [comment]
@veitk This is intended to be used with the Android Emulator, not a real device.  I think you need to run an app on your phone to allow you to set a fake geolocation.  This tool might work with something like that.  Maybe take a look at https://github.com/luv/mockgeofix
