### ISSUE TITLE
com.dpdearing.sandbox.gpsemulator.common.LocationServiceAsync not found

### ISSUE THREAD

**Issue by yuanjifeng** [dpdearing/android-gps-emulator#20]
com.dpdearing.sandbox.gpsemulator.common.LocationServiceAsync not found

**Comment by dpdearing** [comment]
That is a generated source file through the maven configuration.

If you run `mvn compile` it should be found at `android-gps-emulator/target/generated-sources/gwt/com/dpdearing/sandbox/gpsemulator/common`

**Comment by dpdearing** [comment]
I assume this solved the problem?  Closing
